// ── DevOps & ML additions for STATIC_QUESTIONS ────────────────────────────
// Paste these into their respective technical1, technical2 sections

// ═══════════════════════════════════════════════════════════════════════════
// TECHNICAL 1 — DevOps
// ═══════════════════════════════════════════════════════════════════════════
export const technical1_devops = [
  { text: "What is the difference between continuous integration, continuous delivery, and continuous deployment?", options: [], correctAnswer: null, tags: ["CI/CD", "DevOps", "pipeline"], expectedKeywords: ["CI", "CD", "continuous deployment", "pipeline", "automated tests"], rubric: { points: 10, notes: "CI = merge & test often; CD = ready to ship; CDeploy = auto-ship to prod" } },
  { text: "Explain containerisation. What problems does Docker solve compared to running apps directly on a server?", options: [], correctAnswer: null, tags: ["Docker", "containers", "DevOps"], expectedKeywords: ["container", "image", "Dockerfile", "isolation", "portability"], rubric: { points: 10, notes: "Environment isolation, reproducibility, dependency conflicts" } },
  { text: "What is Kubernetes and what problem does it solve on top of Docker?", options: [], correctAnswer: null, tags: ["Kubernetes", "orchestration", "scaling"], expectedKeywords: ["orchestration", "pod", "deployment", "auto-scaling", "service discovery"], rubric: { points: 10, notes: "Docker runs containers; K8s orchestrates them at scale" } },
  { text: "What is Infrastructure as Code (IaC)? How do tools like Terraform or Ansible differ?", options: [], correctAnswer: null, tags: ["IaC", "Terraform", "Ansible"], expectedKeywords: ["IaC", "declarative", "Terraform", "Ansible", "idempotent"], rubric: { points: 10, notes: "Terraform provisions infra declaratively; Ansible configures servers imperatively" } },
  { text: "Explain the concept of a CI/CD pipeline. Walk through the stages of a typical pipeline.", options: [], correctAnswer: null, tags: ["pipeline", "CI/CD", "stages"], expectedKeywords: ["build", "test", "lint", "deploy", "artifact"], rubric: { points: 10, notes: "Source → build → test → package → deploy to staging → prod" } },
  { text: "What is the difference between a VM and a container? When would you use one over the other?", options: [], correctAnswer: null, tags: ["VM", "container", "virtualisation"], expectedKeywords: ["hypervisor", "OS kernel", "lightweight", "startup time", "isolation"], rubric: { points: 10, notes: "VMs virtualise hardware; containers share OS kernel — faster/lighter" } },
  { text: "What is a reverse proxy? How does Nginx act as one, and why is it useful?", options: [], correctAnswer: null, tags: ["Nginx", "reverse proxy", "load balancing"], expectedKeywords: ["reverse proxy", "Nginx", "SSL termination", "load balance", "upstream"], rubric: { points: 10, notes: "Sits in front of app servers, handles SSL, load balancing, caching" } },
  { text: "Explain blue-green and canary deployment strategies. What are the trade-offs?", options: [], correctAnswer: null, tags: ["deployment", "blue-green", "canary"], expectedKeywords: ["blue-green", "canary", "rollback", "traffic split", "zero downtime"], rubric: { points: 10, notes: "Blue-green = instant switch; canary = gradual rollout with rollback" } },
  { text: "What is a Dockerfile? Walk through the key instructions you would use to containerise a Node.js app.", options: [], correctAnswer: null, tags: ["Dockerfile", "Docker", "Node.js"], expectedKeywords: ["FROM", "COPY", "RUN", "EXPOSE", "CMD"], rubric: { points: 10, notes: "Base image, copy files, install deps, expose port, start command" } },
  { text: "What is observability? What is the difference between logs, metrics, and traces?", options: [], correctAnswer: null, tags: ["observability", "monitoring", "logging"], expectedKeywords: ["logs", "metrics", "traces", "Prometheus", "Grafana"], rubric: { points: 10, notes: "Logs = events, metrics = aggregated numbers, traces = request journey" } },
  { text: "What is a Kubernetes Pod, Deployment, and Service? How do they relate to each other?", options: [], correctAnswer: null, tags: ["Kubernetes", "pod", "deployment"], expectedKeywords: ["pod", "deployment", "replica", "service", "selector"], rubric: { points: 10, notes: "Pod = running container(s); Deployment manages replicas; Service exposes them" } },
  { text: "How does DNS work? Walk through what happens when you type a URL in a browser.", options: [], correctAnswer: null, tags: ["DNS", "networking", "browser"], expectedKeywords: ["resolver", "root", "TLD", "authoritative", "A record"], rubric: { points: 10, notes: "Browser → resolver → root → TLD → authoritative NS → IP returned" } },
  { text: "What is a load balancer? What are the differences between Layer 4 and Layer 7 load balancing?", options: [], correctAnswer: null, tags: ["load balancer", "L4", "L7"], expectedKeywords: ["L4", "L7", "round robin", "health check", "sticky session"], rubric: { points: 10, notes: "L4 = TCP/IP; L7 = HTTP-aware, can route by path/header" } },
  { text: "What is the principle of least privilege and how do you apply it in cloud environments?", options: [], correctAnswer: null, tags: ["security", "IAM", "cloud"], expectedKeywords: ["least privilege", "IAM", "role", "policy", "access control"], rubric: { points: 10, notes: "Grant minimum permissions needed; IAM roles, scoped policies" } },
  { text: "What is a message queue? How does something like RabbitMQ or Kafka differ from a REST API call?", options: [], correctAnswer: null, tags: ["message queue", "Kafka", "async"], expectedKeywords: ["queue", "producer", "consumer", "async", "decoupling"], rubric: { points: 10, notes: "Async decoupled; queue buffers messages; Kafka is durable/partitioned" } },
  { text: "What is horizontal pod autoscaling in Kubernetes and how does it work?", options: [], correctAnswer: null, tags: ["Kubernetes", "autoscaling", "HPA"], expectedKeywords: ["HPA", "CPU", "metric", "scale", "threshold"], rubric: { points: 10, notes: "HPA watches metrics, adds/removes pods based on CPU or custom metrics" } },
  { text: "What is SSH and how does public-key authentication work?", options: [], correctAnswer: null, tags: ["SSH", "security", "authentication"], expectedKeywords: ["public key", "private key", "authorized_keys", "challenge", "asymmetric"], rubric: { points: 10, notes: "Server holds public key; client proves ownership of private key" } },
  { text: "What is a VPC? How does subnetting and security groups work in AWS?", options: [], correctAnswer: null, tags: ["VPC", "AWS", "networking"], expectedKeywords: ["VPC", "subnet", "security group", "CIDR", "NAT gateway"], rubric: { points: 10, notes: "VPC = isolated network; public/private subnets; SGs = stateful firewalls" } },
  { text: "Explain the concept of immutable infrastructure. Why is it preferred over mutable servers?", options: [], correctAnswer: null, tags: ["immutable infrastructure", "DevOps"], expectedKeywords: ["immutable", "replace", "config drift", "image", "rollback"], rubric: { points: 10, notes: "Never patch running servers; replace with new image to avoid drift" } },
  { text: "What is GitOps? How does it differ from traditional CI/CD?", options: [], correctAnswer: null, tags: ["GitOps", "ArgoCD", "CI/CD"], expectedKeywords: ["GitOps", "ArgoCD", "declarative", "Git as source of truth", "sync"], rubric: { points: 10, notes: "Git is the single source of truth; ArgoCD reconciles cluster state" } },
];

// ═══════════════════════════════════════════════════════════════════════════
// TECHNICAL 1 — ML (Machine Learning)
// ═══════════════════════════════════════════════════════════════════════════
export const technical1_ml = [
  { text: "What is the difference between supervised, unsupervised, and reinforcement learning?", options: [], correctAnswer: null, tags: ["ML basics", "supervised", "unsupervised"], expectedKeywords: ["supervised", "unsupervised", "reinforcement", "labels", "reward"], rubric: { points: 10, notes: "Supervised=labelled data; unsupervised=patterns; RL=reward signal" } },
  { text: "What is overfitting and underfitting? How do you detect and prevent each?", options: [], correctAnswer: null, tags: ["overfitting", "underfitting", "bias-variance"], expectedKeywords: ["overfitting", "underfitting", "regularisation", "dropout", "validation loss"], rubric: { points: 10, notes: "Overfit=high train/low val; Underfit=poor both; fix with regularisation/more data" } },
  { text: "Explain the bias-variance trade-off in machine learning.", options: [], correctAnswer: null, tags: ["bias-variance", "generalisation"], expectedKeywords: ["bias", "variance", "trade-off", "generalisation", "complexity"], rubric: { points: 10, notes: "High bias=underfit; high variance=overfit; goal is sweet spot" } },
  { text: "What is gradient descent? Explain the difference between batch, mini-batch, and stochastic gradient descent.", options: [], correctAnswer: null, tags: ["gradient descent", "optimisation"], expectedKeywords: ["gradient", "learning rate", "batch", "stochastic", "mini-batch"], rubric: { points: 10, notes: "SGD=1 sample; mini-batch=subset; batch=full dataset per update" } },
  { text: "What is cross-validation and why is it important?", options: [], correctAnswer: null, tags: ["cross-validation", "evaluation"], expectedKeywords: ["k-fold", "train", "validation", "generalisation", "overfitting"], rubric: { points: 10, notes: "k-fold splits data to estimate generalisation performance reliably" } },
  { text: "Explain precision, recall, and F1 score. When would you prioritise recall over precision?", options: [], correctAnswer: null, tags: ["evaluation metrics", "precision", "recall"], expectedKeywords: ["precision", "recall", "F1", "false positive", "false negative"], rubric: { points: 10, notes: "Cancer detection: recall>precision to minimise missed cases" } },
  { text: "What is a confusion matrix? How do you interpret it?", options: [], correctAnswer: null, tags: ["confusion matrix", "evaluation"], expectedKeywords: ["TP", "TN", "FP", "FN", "accuracy"], rubric: { points: 10, notes: "TP/TN/FP/FN quadrant; derive precision, recall, accuracy from it" } },
  { text: "What is regularisation? Explain L1 (Lasso) and L2 (Ridge) regularisation.", options: [], correctAnswer: null, tags: ["regularisation", "L1", "L2"], expectedKeywords: ["L1", "L2", "Lasso", "Ridge", "penalty"], rubric: { points: 10, notes: "L1 creates sparsity; L2 shrinks weights; both penalise large weights" } },
  { text: "What are activation functions in neural networks? Why do we need non-linearity?", options: [], correctAnswer: null, tags: ["activation functions", "neural networks"], expectedKeywords: ["ReLU", "sigmoid", "softmax", "non-linear", "vanishing gradient"], rubric: { points: 10, notes: "Without non-linearity nets collapse to linear; ReLU avoids vanishing gradient" } },
  { text: "What is the difference between a classification and a regression problem?", options: [], correctAnswer: null, tags: ["classification", "regression"], expectedKeywords: ["classification", "regression", "discrete", "continuous", "output"], rubric: { points: 10, notes: "Classification=discrete labels; regression=continuous values" } },
  { text: "What is feature engineering and why is it important?", options: [], correctAnswer: null, tags: ["feature engineering", "ML pipeline"], expectedKeywords: ["feature", "normalisation", "encoding", "selection", "domain knowledge"], rubric: { points: 10, notes: "Better features > better models; encode categoricals, scale numerics" } },
  { text: "What is the difference between bagging and boosting? Give examples of each.", options: [], correctAnswer: null, tags: ["ensemble", "bagging", "boosting"], expectedKeywords: ["bagging", "boosting", "Random Forest", "XGBoost", "variance"], rubric: { points: 10, notes: "Bagging=parallel, reduce variance (RF); Boosting=sequential, reduce bias (XGB)" } },
  { text: "What is a convolutional neural network (CNN)? Why is it well-suited for image data?", options: [], correctAnswer: null, tags: ["CNN", "deep learning", "images"], expectedKeywords: ["convolution", "pooling", "filter", "spatial", "translation invariant"], rubric: { points: 10, notes: "Filters detect local patterns; pooling adds spatial invariance" } },
  { text: "What is transfer learning? When and why would you use a pre-trained model?", options: [], correctAnswer: null, tags: ["transfer learning", "fine-tuning"], expectedKeywords: ["pre-trained", "fine-tune", "features", "small dataset", "ImageNet"], rubric: { points: 10, notes: "Reuse learned features; useful when data is scarce" } },
  { text: "Explain the attention mechanism and why it was important for NLP.", options: [], correctAnswer: null, tags: ["attention", "transformers", "NLP"], expectedKeywords: ["attention", "transformer", "query", "key", "value"], rubric: { points: 10, notes: "Allows model to focus on relevant tokens; basis of transformers" } },
  { text: "What is the difference between a generative and a discriminative model?", options: [], correctAnswer: null, tags: ["generative", "discriminative", "ML"], expectedKeywords: ["generative", "discriminative", "joint probability", "conditional", "GAN"], rubric: { points: 10, notes: "Generative models p(x,y); discriminative model p(y|x)" } },
  { text: "How do you handle imbalanced datasets?", options: [], correctAnswer: null, tags: ["imbalanced data", "SMOTE", "sampling"], expectedKeywords: ["SMOTE", "oversampling", "undersampling", "class weight", "F1"], rubric: { points: 10, notes: "SMOTE, class weights, stratified splits, use F1 not accuracy" } },
  { text: "What is PCA (Principal Component Analysis) and when would you use it?", options: [], correctAnswer: null, tags: ["PCA", "dimensionality reduction"], expectedKeywords: ["PCA", "variance", "eigenvector", "dimensionality", "visualisation"], rubric: { points: 10, notes: "Reduces dimensions while preserving variance; useful before clustering" } },
  { text: "What is a ROC curve and AUC? How do you use them to evaluate a classifier?", options: [], correctAnswer: null, tags: ["ROC", "AUC", "evaluation"], expectedKeywords: ["ROC", "AUC", "TPR", "FPR", "threshold"], rubric: { points: 10, notes: "ROC plots TPR vs FPR at all thresholds; AUC=area; 1.0 is perfect" } },
  { text: "What is the vanishing gradient problem and how do modern architectures address it?", options: [], correctAnswer: null, tags: ["vanishing gradient", "deep learning"], expectedKeywords: ["vanishing gradient", "ReLU", "batch norm", "residual", "LSTM"], rubric: { points: 10, notes: "Gradients shrink through layers; fixed by ReLU, batch norm, skip connections" } },
];

// ═══════════════════════════════════════════════════════════════════════════
// TECHNICAL 2 — DevOps (resume/project-based)
// ═══════════════════════════════════════════════════════════════════════════
export const technical2_devops = [
  { text: "Your resume mentions Docker. Walk me through how you containerised one of your applications and what challenges you faced.", options: [], correctAnswer: null, tags: ["Docker", "containerisation", "project"], expectedKeywords: ["Dockerfile", "image", "layer", "volume", "port"], rubric: { points: 10, notes: "Should discuss multi-stage builds, layer caching, runtime config" } },
  { text: "You listed CI/CD in your skills. Describe the pipeline you set up and how it improved your development workflow.", options: [], correctAnswer: null, tags: ["CI/CD", "GitHub Actions", "pipeline"], expectedKeywords: ["pipeline", "test", "build", "deploy", "GitHub Actions"], rubric: { points: 10, notes: "Trigger on push, run tests, build artifact, deploy to env" } },
  { text: "Walk me through how you would design the deployment architecture for your project on AWS or GCP from scratch.", options: [], correctAnswer: null, tags: ["cloud", "AWS", "architecture"], expectedKeywords: ["EC2", "RDS", "load balancer", "S3", "VPC"], rubric: { points: 10, notes: "VPC, subnets, LB, app servers, managed DB, S3 for assets" } },
  { text: "If your containerised application went down in production, what steps would you take to diagnose and recover?", options: [], correctAnswer: null, tags: ["incident response", "debugging", "Docker"], expectedKeywords: ["logs", "docker logs", "restart", "health check", "rollback"], rubric: { points: 10, notes: "Check logs, inspect container, rollback image, alert team" } },
  { text: "How did you manage secrets and environment variables in your project? What would you improve for production?", options: [], correctAnswer: null, tags: ["secrets", "environment variables", "security"], expectedKeywords: ["env file", "secrets manager", "Vault", "K8s secrets", "never commit"], rubric: { points: 10, notes: ".env locally; AWS Secrets Manager or Vault in prod; never in code" } },
  { text: "Describe how you would implement health checks and auto-restart for your containerised service.", options: [], correctAnswer: null, tags: ["health check", "Docker", "Kubernetes"], expectedKeywords: ["HEALTHCHECK", "liveness probe", "readiness probe", "restart policy"], rubric: { points: 10, notes: "Dockerfile HEALTHCHECK or K8s liveness/readiness probes" } },
  { text: "How would you set up monitoring and alerting for your project in production?", options: [], correctAnswer: null, tags: ["monitoring", "Prometheus", "alerting"], expectedKeywords: ["Prometheus", "Grafana", "alert", "metric", "uptime"], rubric: { points: 10, notes: "Prometheus scrapes metrics, Grafana dashboards, alert on error rate/latency" } },
  { text: "Walk me through how you would handle zero-downtime deployments for your project.", options: [], correctAnswer: null, tags: ["deployment", "zero downtime", "rolling"], expectedKeywords: ["rolling update", "blue-green", "canary", "health check", "load balancer"], rubric: { points: 10, notes: "Rolling updates, readiness probes, LB drains old instances" } },
  { text: "How would you implement a backup and disaster recovery strategy for your application's database?", options: [], correctAnswer: null, tags: ["backup", "disaster recovery", "database"], expectedKeywords: ["snapshot", "automated backup", "RTO", "RPO", "restore"], rubric: { points: 10, notes: "Automated snapshots, cross-region replication, test restores regularly" } },
  { text: "If you were to move your project from a single server to a Kubernetes cluster, what changes would you make?", options: [], correctAnswer: null, tags: ["Kubernetes", "migration", "architecture"], expectedKeywords: ["Deployment", "Service", "Ingress", "ConfigMap", "PersistentVolume"], rubric: { points: 10, notes: "Deployment manifests, Service for networking, Ingress for routing, PV for data" } },
  { text: "How would you implement log aggregation across multiple instances of your service?", options: [], correctAnswer: null, tags: ["logging", "ELK", "aggregation"], expectedKeywords: ["ELK", "Fluentd", "centralised", "structured", "index"], rubric: { points: 10, notes: "Fluentd/Logstash ship to Elasticsearch, Kibana for search" } },
  { text: "Describe how you would set up a staging environment that mirrors production as closely as possible.", options: [], correctAnswer: null, tags: ["staging", "environment", "parity"], expectedKeywords: ["parity", "same config", "infra as code", "seed data", "feature flag"], rubric: { points: 10, notes: "IaC to replicate infra, anonymised prod data, same secrets approach" } },
  { text: "How would you handle database migrations safely in a CI/CD pipeline without downtime?", options: [], correctAnswer: null, tags: ["migrations", "zero downtime", "database"], expectedKeywords: ["migrate", "backward compatible", "rollback", "blue-green", "expand-contract"], rubric: { points: 10, notes: "Expand-contract pattern, backward-compatible changes first, run before deploy" } },
  { text: "How would you implement rate limiting and DDoS protection at the infrastructure level?", options: [], correctAnswer: null, tags: ["security", "rate limiting", "DDoS"], expectedKeywords: ["WAF", "rate limit", "Nginx", "Cloudflare", "IP block"], rubric: { points: 10, notes: "Cloudflare/WAF at edge, Nginx rate limiting, block suspicious IPs" } },
  { text: "Walk me through how you would implement auto-scaling for your backend service based on traffic.", options: [], correctAnswer: null, tags: ["auto-scaling", "cloud", "traffic"], expectedKeywords: ["HPA", "ASG", "CPU", "metric", "scale out"], rubric: { points: 10, notes: "Cloud ASG or K8s HPA, CPU/custom metrics, scale-in cooldown" } },
  { text: "How would you set up a multi-environment Git branching strategy for your project?", options: [], correctAnswer: null, tags: ["GitFlow", "branching", "environments"], expectedKeywords: ["main", "develop", "feature", "staging", "GitFlow"], rubric: { points: 10, notes: "GitFlow or trunk-based, branch per env, protected main" } },
  { text: "What would you do if a deployment introduced a bug and you needed to roll back quickly?", options: [], correctAnswer: null, tags: ["rollback", "incident", "deployment"], expectedKeywords: ["rollback", "previous image", "git revert", "feature flag", "hotfix"], rubric: { points: 10, notes: "Revert to previous container image or Helm chart revision" } },
  { text: "How would you implement network policies in Kubernetes to restrict communication between services?", options: [], correctAnswer: null, tags: ["Kubernetes", "network policy", "security"], expectedKeywords: ["NetworkPolicy", "ingress", "egress", "selector", "namespace"], rubric: { points: 10, notes: "K8s NetworkPolicy restricts pod-to-pod traffic by label selectors" } },
  { text: "How would you optimise Docker image size for your application?", options: [], correctAnswer: null, tags: ["Docker", "optimisation", "image size"], expectedKeywords: ["multi-stage", "alpine", "layer", ".dockerignore", "cache"], rubric: { points: 10, notes: "Multi-stage builds, alpine base, .dockerignore, minimise layers" } },
  { text: "What metrics would you monitor for a Node.js backend running in production on Kubernetes?", options: [], correctAnswer: null, tags: ["monitoring", "Node.js", "Kubernetes"], expectedKeywords: ["CPU", "memory", "latency", "error rate", "event loop lag"], rubric: { points: 10, notes: "CPU/memory, p95 latency, error rate, event loop lag, pod restarts" } },
];

// ═══════════════════════════════════════════════════════════════════════════
// TECHNICAL 2 — ML (resume/project-based)
// ═══════════════════════════════════════════════════════════════════════════
export const technical2_ml = [
  { text: "Your resume mentions a machine learning project. Walk me through your model selection process — how did you choose the algorithm?", options: [], correctAnswer: null, tags: ["model selection", "ML project"], expectedKeywords: ["baseline", "experiment", "accuracy", "complexity", "trade-off"], rubric: { points: 10, notes: "Should mention baseline, comparison of models, metric-driven selection" } },
  { text: "How did you split your dataset? Why did you choose that split ratio and strategy?", options: [], correctAnswer: null, tags: ["train test split", "cross-validation"], expectedKeywords: ["train", "validation", "test", "stratified", "leakage"], rubric: { points: 10, notes: "Stratified split, separate test set never touched, no data leakage" } },
  { text: "Walk me through the data preprocessing steps you applied in your ML project.", options: [], correctAnswer: null, tags: ["preprocessing", "feature engineering", "pipeline"], expectedKeywords: ["normalise", "encode", "missing values", "pipeline", "impute"], rubric: { points: 10, notes: "Handle nulls, encode categoricals, scale numerics, Pipeline to avoid leakage" } },
  { text: "How did you evaluate your model's performance? Which metrics did you use and why?", options: [], correctAnswer: null, tags: ["evaluation", "metrics", "ML project"], expectedKeywords: ["accuracy", "F1", "AUC", "RMSE", "cross-validation"], rubric: { points: 10, notes: "Metric choice driven by problem type and class imbalance" } },
  { text: "Did your model overfit? How did you detect it and what did you do to fix it?", options: [], correctAnswer: null, tags: ["overfitting", "regularisation", "project"], expectedKeywords: ["train val gap", "regularisation", "dropout", "early stopping", "data augmentation"], rubric: { points: 10, notes: "Monitor train vs val loss, apply regularisation or gather more data" } },
  { text: "How did you handle missing or noisy data in your dataset?", options: [], correctAnswer: null, tags: ["missing data", "data cleaning"], expectedKeywords: ["impute", "mean", "median", "drop", "indicator feature"], rubric: { points: 10, notes: "Mean/median/mode imputation, KNN imputer, or create missing indicator" } },
  { text: "Walk me through how you tuned hyperparameters in your project. What search strategy did you use?", options: [], correctAnswer: null, tags: ["hyperparameter tuning", "GridSearch", "Optuna"], expectedKeywords: ["GridSearchCV", "RandomSearch", "Optuna", "learning rate", "cross-val"], rubric: { points: 10, notes: "GridSearch for small spaces, Optuna/Bayesian for large; always CV" } },
  { text: "How did you deploy your trained model so that it could serve predictions in real time?", options: [], correctAnswer: null, tags: ["model deployment", "serving", "FastAPI"], expectedKeywords: ["pickle", "FastAPI", "Flask", "Docker", "endpoint"], rubric: { points: 10, notes: "Serialise model, wrap in REST API, containerise, deploy behind LB" } },
  { text: "How did you handle class imbalance in your classification project?", options: [], correctAnswer: null, tags: ["class imbalance", "SMOTE", "sampling"], expectedKeywords: ["SMOTE", "class_weight", "oversampling", "undersampling", "F1"], rubric: { points: 10, notes: "SMOTE or class_weight parameter; use F1/AUC not accuracy" } },
  { text: "If your model's performance degraded after deployment, what steps would you take to debug it?", options: [], correctAnswer: null, tags: ["model monitoring", "data drift", "debugging"], expectedKeywords: ["data drift", "feature drift", "retrain", "monitor", "distribution shift"], rubric: { points: 10, notes: "Check for data/concept drift, compare feature distributions, retrain" } },
  { text: "How did you ensure your model was not memorising the training data?", options: [], correctAnswer: null, tags: ["generalisation", "overfitting", "validation"], expectedKeywords: ["held-out test", "k-fold", "validation loss", "regularisation", "ablation"], rubric: { points: 10, notes: "Separate test set, k-fold CV, monitor val loss during training" } },
  { text: "How did you approach feature selection in your project? What techniques did you use?", options: [], correctAnswer: null, tags: ["feature selection", "importance", "ML"], expectedKeywords: ["feature importance", "correlation", "RFE", "SHAP", "mutual information"], rubric: { points: 10, notes: "Correlation matrix, tree feature importance, SHAP, RFE" } },
  { text: "Your resume mentions a deep learning component. How did you choose the architecture and training parameters?", options: [], correctAnswer: null, tags: ["deep learning", "architecture", "hyperparameters"], expectedKeywords: ["layers", "learning rate", "batch size", "optimizer", "scheduler"], rubric: { points: 10, notes: "Start with proven architecture, tune LR and batch size first" } },
  { text: "How would you explain your model's predictions to a non-technical stakeholder?", options: [], correctAnswer: null, tags: ["explainability", "SHAP", "stakeholder"], expectedKeywords: ["SHAP", "LIME", "feature importance", "explain", "business language"], rubric: { points: 10, notes: "SHAP values, plain language feature impact, avoid jargon" } },
  { text: "If you had 10x more data available, how would your approach to the project change?", options: [], correctAnswer: null, tags: ["scalability", "data", "deep learning"], expectedKeywords: ["deep learning", "batch training", "distributed", "retrain", "generalise"], rubric: { points: 10, notes: "More data enables deeper models, reduce regularisation, distributed training" } },
  { text: "How did you version your datasets and models in your project?", options: [], correctAnswer: null, tags: ["MLOps", "versioning", "DVC"], expectedKeywords: ["DVC", "MLflow", "version", "artifact", "experiment tracking"], rubric: { points: 10, notes: "DVC for data, MLflow for experiments and model registry" } },
  { text: "What would you monitor in a production ML system to detect when the model needs retraining?", options: [], correctAnswer: null, tags: ["model monitoring", "drift", "MLOps"], expectedKeywords: ["data drift", "prediction drift", "accuracy", "retrain trigger", "Evidently"], rubric: { points: 10, notes: "Track feature distributions, output drift, accuracy decay over time" } },
  { text: "How would you design an A/B test to compare your new model against the existing one in production?", options: [], correctAnswer: null, tags: ["A/B testing", "ML", "deployment"], expectedKeywords: ["traffic split", "control", "treatment", "statistical significance", "metric"], rubric: { points: 10, notes: "Split traffic, define success metric, run until statistical significance" } },
  { text: "Walk me through your data pipeline — how did data get from raw source to model input?", options: [], correctAnswer: null, tags: ["data pipeline", "ETL", "ML"], expectedKeywords: ["ingest", "transform", "validate", "feature store", "pipeline"], rubric: { points: 10, notes: "Ingest → clean → validate → engineer features → load to training" } },
  { text: "What ethical considerations did you think about when building your ML model?", options: [], correctAnswer: null, tags: ["ML ethics", "bias", "fairness"], expectedKeywords: ["bias", "fairness", "explainability", "privacy", "disparate impact"], rubric: { points: 10, notes: "Demographic bias, disparate impact, GDPR, model transparency" } },
];

// ═══════════════════════════════════════════════════════════════════════════
// STATIC TRANSCRIPTS — DevOps (technical1 and technical2, 20 each)
// ═══════════════════════════════════════════════════════════════════════════
const STATIC_TRANSCRIPTS_devops_t1 = [
  "CI means developers merge their code frequently and automated tests run on every commit to catch integration bugs early. Continuous delivery means the codebase is always in a releasable state and deployment to production can happen with a button press. Continuous deployment goes further and automatically ships every passing build to production without any manual gate.",
  "Docker solves the it works on my machine problem by packaging the application and all its dependencies into a container image. Unlike a traditional server setup where library versions clash, each container is isolated. You define the environment once in a Dockerfile and it runs identically on a developer laptop and in production.",
  "Docker gets a single container running but does not handle running hundreds of them, restarting crashed ones, distributing traffic, or rolling updates. Kubernetes orchestrates a fleet of containers across multiple nodes. It schedules pods, ensures desired replica counts, exposes services, and provides self-healing if a node goes down.",
  "Infrastructure as Code means your servers, networks, and databases are defined in version-controlled files rather than set up manually. Terraform provisions the underlying infrastructure declaratively, you describe what you want and it figures out how to get there. Ansible then configures the running servers using imperative playbooks.",
  "A typical pipeline starts when a developer pushes code. The CI server builds the application, runs unit and integration tests, then runs a linter. If all pass it packages the artifact as a Docker image and pushes it to a registry. A deploy stage then updates the staging environment and after manual or automated approval it deploys to production.",
  "A virtual machine includes a full guest operating system running on top of a hypervisor. This means hundreds of megabytes of overhead and slow boot times. A container shares the host OS kernel so it starts in milliseconds and uses far less memory. VMs are better for full OS isolation or running different operating systems; containers are better for microservices.",
  "A reverse proxy sits in front of your application servers and forwards client requests to them. Nginx as a reverse proxy handles SSL termination so the backend only needs to deal with plain HTTP. It also load balances across multiple upstream instances, caches static responses, and protects the backend from direct internet exposure.",
  "Blue-green deployments run two identical production environments. You deploy to green while blue serves traffic, verify green is healthy, then switch the load balancer. Rollback is instant by pointing back to blue. Canary deployment routes a small percentage of traffic to the new version first, gradually increasing it. This limits the blast radius of a bad release.",
  "The Dockerfile starts with a FROM Node image. I copy the package.json first and run npm install before copying the rest of the source code. This exploits Docker layer caching so dependencies are only reinstalled when package.json changes. EXPOSE declares the port and CMD specifies the startup command.",
  "Observability is the ability to understand internal system state from external outputs. Logs are discrete time-stamped events recording what happened. Metrics are aggregated numerical measurements over time like request rate or error rate. Traces follow a single request through multiple services showing where latency was spent. All three together give you a complete picture.",
  "A Pod is the smallest deployable unit in Kubernetes and wraps one or more containers. A Deployment manages a set of identical Pods, ensuring the desired number of replicas are running and handling rolling updates. A Service provides a stable DNS name and load balances traffic across the Pods behind it regardless of which node they are on.",
  "When you type a URL, the browser checks its local DNS cache first. If not found it queries the recursive resolver provided by your ISP or a public one like 8.8.8.8. The resolver walks from root servers to TLD nameservers like .com to authoritative nameservers for the domain to get the final IP address which is returned to the browser.",
  "Layer 4 load balancing works at the transport level using TCP and UDP without inspecting the request content. It is very fast and low overhead. Layer 7 operates at the application layer, reading HTTP headers, URLs, and cookies. This allows routing based on path so requests to slash API go to backend servers while slash static goes to a CDN origin.",
  "The principle of least privilege means every service or user gets only the minimum permissions needed to do its job. In AWS I create IAM roles with specific policies for each service rather than giving admin access. An EC2 instance that only reads from S3 should have a role with only GetObject on that specific bucket.",
  "A message queue decouples the producer from the consumer. Unlike a direct REST call where the caller waits for a response, a queue stores messages so consumers process them asynchronously at their own pace. RabbitMQ is a traditional broker for task queues. Kafka is a distributed log designed for high throughput and durable event streaming across many consumers.",
  "The Horizontal Pod Autoscaler watches a target metric such as average CPU utilisation across Pods. When the metric exceeds a threshold the HPA calculates how many replicas are needed and scales the Deployment up. When load drops it scales back down after a cooldown period. You can also configure custom metrics from Prometheus for more sophisticated scaling.",
  "SSH uses asymmetric cryptography. You generate a key pair: the private key stays on your machine and the public key is placed in the server's authorized_keys file. When you connect the server sends a challenge encrypted with your public key. Only you can decrypt it with your private key and send back the correct response, proving identity without a password.",
  "A VPC is a logically isolated network in the cloud. Within it you create public subnets with internet gateway access for load balancers and private subnets without direct internet access for application servers and databases. Security groups act as stateful firewalls at the instance level, controlling inbound and outbound traffic by port and IP range.",
  "Immutable infrastructure means once a server is deployed you never patch or modify it. If you need a change you build a new image, deploy instances from it, and terminate the old ones. This eliminates configuration drift where servers gradually diverge from their intended state. Rollback is as simple as redeploying the previous image.",
  "GitOps uses Git as the single source of truth for both application code and infrastructure configuration. Tools like ArgoCD continuously compare the desired state in Git with the actual cluster state and automatically reconcile differences. Unlike traditional CI/CD where a pipeline pushes changes, GitOps pulls and applies them declaratively.",
];

const STATIC_TRANSCRIPTS_devops_t2 = [
  "I wrote a multi-stage Dockerfile for the Node.js backend. The first stage used a full Node image to install dependencies and build. The second stage used a smaller Alpine image and only copied the built output. This reduced the final image from over 800 MB to under 150 MB. The main challenge was ensuring all native modules compiled correctly in the Alpine environment.",
  "I set up a GitHub Actions pipeline that triggers on every push to main. It runs the test suite first and if that passes it builds a Docker image tagged with the commit SHA. It then pushes the image to Docker Hub and deploys to a staging server via SSH. The whole pipeline runs in under three minutes.",
  "I would start with a VPC with public and private subnets across two availability zones. The load balancer sits in the public subnets, Node.js EC2 instances in private subnets, and MongoDB in a separate private subnet. S3 handles static assets and uploaded files. Route 53 manages DNS and an ACM certificate handles SSL termination at the load balancer.",
  "First I would check the container logs with docker logs and look for error messages. Then I would inspect the container status and see if the health check is failing. If the image is bad I would roll back to the previous tagged image with docker pull and redeploy. I would also check host resource utilisation to rule out memory or CPU exhaustion.",
  "During development I used a dot env file excluded from Git. For the project demo I stored secrets in environment variables injected at runtime. For a production system I would use AWS Secrets Manager and have the application fetch secrets at startup, rotating them automatically without redeployment.",
  "In the Dockerfile I added a HEALTHCHECK instruction that runs a curl against the slash health endpoint every thirty seconds. If it fails three times the container is marked unhealthy and Docker restarts it. The restart policy is set to on-failure with a max retry count. In Kubernetes I would use liveness and readiness probes instead.",
  "I would set up Prometheus to scrape metrics from the Node.js app using the prom-client library and from MongoDB exporter. Grafana dashboards would show request rate, error rate, and p95 latency. I would configure alerts that fire when error rate exceeds one percent or when response time goes over 500 milliseconds for more than two minutes.",
  "I would use a rolling deployment strategy. The load balancer health check ensures new instances are ready before old ones receive no more traffic. In Kubernetes a Deployment rolling update brings up new pods and only terminates old ones after the readiness probe passes. This guarantees zero downtime without needing a separate blue environment.",
  "I would configure daily automated snapshots of the MongoDB Atlas cluster with a 7 day retention period. For critical data I would also enable continuous backup with point-in-time recovery. Cross-region snapshot copies protect against regional outages. I would document the restore procedure and test it in staging monthly.",
  "I would create Kubernetes Deployment manifests for each service specifying the container image, resource limits, and replica count. A Service manifest exposes each Deployment internally. An Ingress controller handles routing from the external load balancer to the correct service by path. ConfigMaps hold non-secret config and Secrets hold credentials. PersistentVolumeClaims handle stateful data.",
  "I would configure each container to write structured JSON logs to stdout. A Fluentd daemonset on each Kubernetes node would collect those logs and forward them to an Elasticsearch cluster. Kibana provides a search interface. This centralises logs from all replicas so you can search across instances by request ID or error message.",
  "I would use Terraform to create the staging environment from the same modules as production with smaller instance types. I would use anonymised snapshots of production data seeded into the staging database. The same Docker images are deployed so the environment is identical except for scale. Feature flags allow testing new features in staging without affecting production.",
  "I use the expand-contract pattern. First deploy a backward-compatible schema change such as adding a nullable column. Then deploy the application code that uses it. Finally remove the old column in a separate migration after confirming no code references it. This allows zero-downtime migrations where old and new app versions run simultaneously.",
  "At the edge I would use Cloudflare in front of the application for DDoS protection and bot mitigation. At the application layer Nginx would enforce per-IP rate limits using the limit_req module. For authenticated APIs I would add a Redis-backed rate limiter in the application middleware tracking requests per API key with a sliding window.",
  "I would configure a Kubernetes Horizontal Pod Autoscaler targeting 70 percent average CPU utilisation. The cluster itself would use a node autoscaler to add EC2 instances when pod scheduling fails due to insufficient capacity. I would define minimum replicas of two for high availability and a maximum based on cost constraints.",
  "I use a branch-per-environment strategy. Feature branches merge into develop for integration testing. Develop merges into staging which triggers deployment to the staging environment. Release candidates merge into main which triggers production deployment. Main is protected and requires passing CI and one approving review before merging.",
  "If a critical bug was introduced I would immediately roll back by updating the Kubernetes Deployment to the previous image tag. This triggers a rolling update back to the known-good version and takes under a minute. Once the rollback is live I would create a hotfix branch to fix the bug properly and go through the normal deploy process.",
  "I would define Kubernetes NetworkPolicy resources that default to deny all ingress and egress. Then I would add explicit allow rules so the frontend service can reach the API on port 3000, the API can reach MongoDB on port 27017, and nothing else. This enforces least privilege at the network layer inside the cluster.",
  "I use multi-stage builds where the first stage installs all dev dependencies and compiles. The second stage starts from a minimal Alpine image and copies only the production node_modules and compiled output. I maintain a thorough dot dockerignore to exclude test files and local configs. This keeps the final image under 100 MB.",
  "For a Node.js service I would monitor CPU and memory usage at the pod and node level, HTTP request rate and error rate broken down by status code, p50 and p95 response latency, event loop lag using prom-client, and the number of pod restarts which often signals memory leaks or crash loops. I would also watch MongoDB connection pool saturation.",
];

const STATIC_TRANSCRIPTS_ml_t1 = [
  "Supervised learning trains a model on labelled input-output pairs to predict outputs for new inputs. Examples include regression and classification. Unsupervised learning finds patterns in unlabelled data like clustering and dimensionality reduction. Reinforcement learning trains an agent through trial and error using a reward signal to guide behaviour.",
  "Overfitting is when a model learns the training data too well including its noise and fails to generalise. You detect it when training accuracy is high but validation accuracy is low. Prevention techniques include regularisation, dropout, early stopping, and more training data. Underfitting is when the model is too simple and performs poorly on both train and validation sets.",
  "Bias is error from incorrect assumptions in the learning algorithm, causing it to miss relevant relationships. Variance is error from sensitivity to small fluctuations in training data. A high bias model underfits; a high variance model overfits. The trade-off means reducing bias often increases variance. The goal is finding the complexity that balances both for good generalisation.",
  "Gradient descent iteratively adjusts model parameters in the direction that minimises the loss function. Batch gradient descent computes the gradient over the entire dataset, which is stable but slow. Stochastic uses one random sample per update, fast but noisy. Mini-batch uses a small subset, balancing speed and stability. Most deep learning uses mini-batch with batch sizes like 32 or 256.",
  "Cross-validation estimates how well a model generalises to unseen data. K-fold splits the data into k folds and trains k times, each time using a different fold as validation and the rest as training. The k validation scores are averaged for a reliable estimate. This is more robust than a single train-val split, especially for small datasets.",
  "Precision is the fraction of positive predictions that are actually positive. Recall is the fraction of actual positives that were correctly identified. F1 is their harmonic mean. In cancer detection I would prioritise recall because missing a real case is far worse than a false alarm. In spam detection I might prioritise precision to avoid marking legitimate emails as spam.",
  "A confusion matrix is a grid showing true positives, true negatives, false positives, and false negatives. From it you derive precision, recall, accuracy, and specificity. It is particularly useful for imbalanced classes where accuracy alone can be misleading. For a dataset with 99 percent negatives a model predicting all negatives is 99 percent accurate but useless.",
  "Regularisation adds a penalty term to the loss function to discourage overly complex models. L1 or Lasso adds the absolute value of weights, encouraging sparsity by pushing some weights to exactly zero, effectively performing feature selection. L2 or Ridge adds the square of weights, shrinking all weights toward zero without eliminating them completely.",
  "Activation functions introduce non-linearity, without which a neural network regardless of depth collapses to a single linear transformation. ReLU returns zero for negative inputs and the input for positive inputs, which is computationally simple and avoids the vanishing gradient problem. Sigmoid and tanh saturate at extremes causing gradients to vanish. Softmax converts outputs to probabilities for multi-class classification.",
  "Classification predicts a discrete label such as spam or not spam, cat or dog. Regression predicts a continuous value such as house price or temperature. The loss functions differ: classification typically uses cross-entropy, regression uses mean squared error. Evaluation metrics also differ: accuracy and F1 for classification, RMSE and MAE for regression.",
  "Feature engineering transforms raw data into inputs that better represent the underlying problem to the model. This includes encoding categorical variables, scaling numerical features, creating polynomial features, and extracting domain-specific signals. A well-engineered feature set can make a simple model outperform a complex one on poor features.",
  "Bagging trains multiple models in parallel on different random subsets of the training data and averages their predictions. This reduces variance. Random Forest is the classic bagging algorithm using decision trees with random feature subsets. Boosting trains models sequentially where each new model corrects the errors of the previous one, reducing bias. XGBoost and LightGBM are the leading boosting frameworks.",
  "CNNs use convolutional filters that slide over input images detecting local patterns like edges, textures, and shapes. Because the same filter is applied everywhere the network learns translation-invariant features with far fewer parameters than a fully connected network. Pooling layers reduce spatial dimensions preserving the most important information. Deep CNNs stack these to detect increasingly abstract features.",
  "Transfer learning reuses the weights of a model pre-trained on a large dataset and fine-tunes it for a new task. For images, models pre-trained on ImageNet already know how to detect edges, textures, and objects. You replace only the final classification layer and retrain on your small dataset. This dramatically reduces training time and data requirements.",
  "The attention mechanism allows the model to weigh the importance of different positions in the input when generating each output token. Instead of compressing the entire input into a fixed vector, attention queries the full input sequence and focuses on the most relevant parts. Transformers use self-attention to build context-aware representations of each token relative to all others.",
  "Discriminative models learn the conditional probability of the label given the input, the decision boundary between classes. Examples are logistic regression and SVMs. Generative models learn the joint probability of data and labels and can generate new samples. Examples are VAEs and GANs. Generative models can handle missing data and generate synthetic examples.",
  "I would first try oversampling the minority class using SMOTE which creates synthetic examples by interpolating between existing ones. Alternatively I would use the class_weight parameter in scikit-learn to penalise misclassifying the minority class more heavily. I would evaluate using F1 score and AUC-ROC rather than accuracy to avoid misleading results.",
  "PCA projects data onto the directions of maximum variance called principal components. It reduces dimensionality by keeping only the top k components that explain most of the variance. Use cases include reducing noise, visualising high-dimensional data in 2D, and speeding up training. The trade-off is interpretability since components are linear combinations of original features.",
  "The ROC curve plots true positive rate against false positive rate at every possible decision threshold. AUC is the area under this curve. An AUC of 1.0 means perfect classification, 0.5 means no better than random. AUC is threshold-independent so it measures overall discriminative ability. I use it when comparing models or when the optimal threshold is not yet known.",
  "In deep networks gradients are multiplied through many layers during backpropagation. If activations like sigmoid saturate, their gradients approach zero and the signal vanishes before reaching early layers, making training very slow. ReLU avoids this for positive activations. Batch normalisation stabilises activations. Residual connections create shortcuts that let gradients flow directly to earlier layers.",
];

const STATIC_TRANSCRIPTS_ml_t2 = [
  "I started with a logistic regression baseline to understand the difficulty of the problem. Then I compared a random forest and an XGBoost model using 5-fold cross-validation with F1 score as the metric. XGBoost performed best so I proceeded with it. I chose based on metric scores rather than perceived model prestige.",
  "I used a stratified 70-10-20 split for train, validation, and test. Stratified ensured class proportions were preserved. I treated the test set as completely held-out and only evaluated on it once at the very end to get an unbiased estimate. All preprocessing and hyperparameter decisions were made using the training and validation sets only.",
  "First I identified and handled missing values using median imputation for numerical columns and mode for categoricals. I then one-hot encoded categorical features and applied standard scaling to numerical ones. Crucially I fit all transformers on the training set only and used transform on validation and test to prevent data leakage.",
  "For a binary classification problem I tracked F1 score and AUC-ROC because the classes were imbalanced. Accuracy was misleading since predicting all negatives gave 90 percent accuracy. I also looked at the precision-recall curve to find the optimal threshold. Final model selection was driven by AUC on the held-out validation fold in cross-validation.",
  "My validation loss started increasing after epoch 15 while training loss continued decreasing, a clear sign of overfitting. I added L2 regularisation and dropout of 0.3 after each dense layer. I also implemented early stopping with a patience of 5 epochs. Combined these brought the train-validation gap from 12 percent down to 3 percent.",
  "About 15 percent of records had missing values in three features. For numerical features I used median imputation since the distributions were skewed. For the categorical feature I imputed with the most frequent value. I also added a binary indicator column for each imputed feature so the model could learn that missingness itself was informative.",
  "I used RandomizedSearchCV first to narrow the hyperparameter space, testing 50 random combinations with 5-fold cross-validation. I then ran Optuna on the promising region for Bayesian optimisation. I tuned learning rate, max depth, and subsample ratio. The final model improved F1 by 4 percent over the default parameters.",
  "I serialised the trained model using joblib and built a FastAPI application with a POST endpoint that accepts JSON input, preprocesses it through the same pipeline used during training, and returns the prediction and probability. I containerised it with Docker and deployed behind an Nginx reverse proxy so it could serve concurrent requests.",
  "The minority class had a 1 to 9 ratio. I applied SMOTE on the training set only after splitting. I also used the class_weight equals balanced parameter in scikit-learn models. I evaluated using the macro F1 score which weights each class equally regardless of support. This combination improved minority class recall from 42 percent to 71 percent.",
  "I would check for data drift first by comparing the statistical distributions of incoming features against the training distribution using tools like Evidently AI. If feature distributions shifted significantly that explains the degradation. I would then retrain on more recent data. I would also check if any upstream data pipeline changes altered feature encoding.",
  "I used a separate 20 percent held-out test set that was never used during training, validation, or hyperparameter tuning. I ran 5-fold cross-validation on the remaining 80 percent for model selection. The similar scores across folds and between CV and test set gave me confidence the model was generalising rather than memorising.",
  "I started with correlation analysis to remove highly correlated features above 0.95. I then used tree-based feature importances from the random forest to rank features. I removed the bottom 20 percent and retrained. Finally I applied SHAP to understand which features were actually driving predictions, which revealed two counterintuitive but highly impactful features.",
  "I started with a ResNet-50 pre-trained on ImageNet, replacing the final classification layer. I froze all convolutional blocks for the first 5 epochs and only trained the head. Then I unfroze the last two blocks and fine-tuned with a much smaller learning rate. I used a cosine annealing scheduler and batch size of 32. Data augmentation was critical to prevent overfitting.",
  "I would use SHAP values to explain individual predictions in terms of feature contributions. For a loan approval model I would say this application was rejected primarily because the debt-to-income ratio was above the threshold and the credit history was short. I would avoid technical terms and focus on which factors pushed the score up or down.",
  "With 10 times more data I would explore deeper neural network architectures that currently overfit on the smaller dataset. I would reduce regularisation strength and dropout rates. I would also consider distributed training across multiple GPUs to keep training times manageable. More data generally means better generalisation so I would also raise the complexity ceiling.",
  "I used DVC to version datasets alongside the code in Git. Model artifacts were logged to MLflow with their hyperparameters, training metrics, and feature importances. Each experiment had a unique run ID. This allowed me to reproduce any past model exactly and compare runs in the MLflow UI to identify what changes drove improvements.",
  "I would track the mean and standard deviation of each input feature in production and compare them to the training distribution daily using statistical tests. I would also monitor prediction distribution shifts and accuracy decay if ground truth labels are available with a delay. When drift is detected I would trigger an automated retraining pipeline.",
  "I would split incoming traffic 90 to 10 between the control model and the new model. I would define the primary success metric upfront, for example conversion rate or recommendation click-through. I would run the experiment until I reached statistical significance at a 95 percent confidence level, accounting for multiple testing. Only then would I make a rollout decision.",
  "Raw data was ingested from a CSV dump into a staging area. A Python script cleaned it, handled missing values, and applied feature engineering. The output was saved as a parquet file. A second step split it into train and test sets and applied the sklearn Pipeline which fit transformers on train and transformed both. The final arrays were saved and fed to the training script.",
  "I thought about demographic bias in the training data and checked whether the model performed equally well across age groups and genders. I used disaggregated evaluation metrics rather than just overall accuracy. I also ensured personally identifiable information was removed before training. Explainability mattered because decisions affected real people, so I made model reasoning auditable.",
];